language: c++
sudo: false

git:
  depth: 10
  submodules: false

matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=g++-5 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=g++-6 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
          - g++-6
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=g++-7 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=g++-8 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - g++-8
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug ENABLE_IO=NO
      compiler: gcc
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=clang++-3.6 CMAKE_BUILD_TYPE=Debug
      compiler: clang
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
          packages:
          - clang-3.6
          - libboost1.55-all-dev

    - os: linux
      env: COMPILER=clang++-3.7 CMAKE_BUILD_TYPE=Debug
      compiler: clang
      addons:
        apt:
          sources:
          - boost-latest
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
          packages:
          - clang-3.7
          - libboost1.55-all-dev

    #- os: linux
    #  env: COMPILER=clang++-3.8 CMAKE_BUILD_TYPE=Debug
    #  compiler: clang
    #  addons:
    #    apt:
    #      sources:
    #      - boost-latest
    #      - ubuntu-toolchain-r-test
    #      - llvm-toolchain-precise-3.8
    #      packages:
    #      - clang-3.8
    #      - libboost1.55-all-dev

    #- os: linux
    #  env: COMPILER=clang++-3.9 CMAKE_BUILD_TYPE=Debug
    #  compiler: clang
    #  addons:
    #    apt:
    #      sources:
    #      - boost-latest
    #      - ubuntu-toolchain-r-test
    #      - llvm-toolchain-precise-3.9
    #      packages:
    #      - clang-3.9
    #      - libboost1.55-all-dev

    #- os: linux
    #  env: COMPILER=clang++-3.9 CMAKE_BUILD_TYPE=Release
    #  compiler: clang
    #  addons:
    #    apt:
    #      sources:
    #      - boost-latest
    #      - ubuntu-toolchain-r-test
    #      - llvm-toolchain-precise-3.9
    #      packages:
    #      - clang-3.9
    #      - libboost1.55-all-dev

    #- os: linux
    #  env: COMPILER=clang++-4.0 CMAKE_BUILD_TYPE=Debug
    #  compiler: clang
    #  addons:
    #    apt:
    #      sources:
    #      - boost-latest
    #      - ubuntu-toolchain-r-test
    #      - llvm-toolchain-precise-4.0
    #      packages:
    #      - clang-4.0
    #      - libboost1.55-all-dev

install:
  - CMAKE_VERSION="cmake-3.11.4-Linux-x86_64"
  - curl -O https://cmake.org/files/v3.11/${CMAKE_VERSION}.tar.gz
  - tar -xf ${CMAKE_VERSION}.tar.gz
  - rm -f ${CMAKE_VERSION}.tar.gz
  - export PATH=${PWD}/${CMAKE_VERSION}/bin:${PATH}

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - ${COMPILER} --version
  - cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..

script:
  - make
  - make unittest
  - make test

