language: c++
sudo: false

git:
  depth: 10
  submodules: false

matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: COMPILER=g++-5
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

    - os: linux
      env: COMPILER=clang++-3.6
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
          packages:
          - clang-3.6

install:
  # install a recent cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.2.3-Linux-x86_64.tar.gz
  - rm -f cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=${PWD}/cmake-3.2.3-Linux-x86_64/bin:${PATH}

before_script:
  - mkdir build
  - cd build
  - CXX=${COMPILER} cmake ..

script:
  - ${CXX} --version
  - make
  - make unittest
  - make test

