language: cpp
compiler:
  - gcc
  - clang
sudo: false
os: linux

matrix:
  include:
    # clang 3.7
    - env: COMPILER=clang++-3.7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise # latest
          packages:
          - gcc-4.9
          - g++-4.9
          - clang-3.7
    # gcc 4.9
    - env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

install:
  # install a recent cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.2.3-Linux-x86_64.tar.gz
  - rm -f cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=${PWD}/cmake-3.2.3-Linux-x86_64/bin:${PATH}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make unittest

